theme: jekyll-theme-architect
title: "Microdegree"

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "https://microdegree.work"

  # Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/img/avatar-icon.png"
